server:
  port: 8775
  
  
  
spring:
  application:
    name: service-ribbon
    

eureka:
  client:
    service-url:
    #连接设置了security  有账号密码的注册中心
    #  defaultZone: http://lht:lht@discovery1:8761/eureka/,http://lht:lht@discovery2:8762/eureka/,http://lht:lht@discovery3:8763/eureka/
       defaultZone: http://lht:lht@localhost:8761/eureka/
     
     
#在Spring Cloud Eureka中，可以把Eureka客户端的健康检测交给spring-boot-actuator模块的health端点，以实现更加全面的健康状态维护，设置方式如下：
#（1）      在pom.xml中引入spring-boot-starter-actuator模块的依赖
#（2）      在application.properties中增加参数配置eureka.client.healthcheck.enabled=true
