spring:
  profiles:
    active: single
  security:
    user:
      name: lht
      password: lht

      
      
#-----如果自定义了 context-path 则需要将 健康检查 和状态页面 设置成相应的路径 如下-------
#server:
#  servlet:
#    context-path: /xxx
    
#eureka:
#  instance:
#    health-check-url-path: ${server.servlet.context-path}/health 
#    status-page-url-path: ${server.servlet.context-path}/info